### ISSUE TITLE
Unable to Run

### ISSUE THREAD

**Issue by Hbxuan** [brada/zhang#1]
I tried check_caltag.m but I don't know what iPt and wPt mean. 
I do not know how to calib camera with these programs.
It is unfriendly to people who wants to test the program.
Could you please to add some notes?

**Comment by brada** [comment]
The code in this repo was designed to process data generated by [brada/caltag](https://github.com/brada/caltag), which outputs the iPt and wPt arrays. You can take a look at the README or source over there for more details. In summary, iPt are the image-space coordinates of the calibration points (i.e. <x,y> pixel coordinates) and they correspond to wPt (world-space points) which are the <u,v> coordinates on the physical planar target filmed by the cameras. By "calibration points"/"world-space points" I am referring to the saddle points on the chequerboard pattern.
